# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Hourly Matrix Python Workflow

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ Runs every hour
  workflow_dispatch:      # 🔘 Allows manual trigger too

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10   # ⏱️ Each job times out after 15 minutes
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                   11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running instance ${{ matrix.instance }}"
          python app.py
